// <auto-generated />
using CertificateNumberGenerator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CertificateNumberGenerator.Migrations
{
    [DbContext(typeof(APIDBContext))]
    partial class APIDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CertificateNumberGenerator.Models.CertificationScheme", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("CHARACTER VARYING(100)");

                    b.Property<string>("prefix")
                        .HasColumnType("CHARACTER VARYING(20)");

                    b.Property<string>("number")
                        .HasColumnType("CHARACTER VARYING(30)");

                    b.Property<string>("suffix")
                        .HasColumnType("CHARACTER VARYING(20)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("CHARACTER VARYING(250)");

                    b.HasKey("name", "prefix", "number", "suffix");

                    b.ToTable("CertificationSchemes");
                });
#pragma warning restore 612, 618
        }
    }
}
